name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: set_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
        
      - name: Build Docker image
        run: |
         docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.set_tag.outputs.tag }} ./my-strapi-app

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.set_tag.outputs.tag }}

      - name: Save image tag for CD
        run: echo "image_tag=${{ steps.set_tag.outputs.tag }}" >> $GITHUB_ENV
