name: CD - Deploy with Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show repo files
        run: ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: ./task5_terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./task5_terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./task5_terraform
        run: terraform apply -auto-approve tfplan
