name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Docker image tag (from CI pipeline)"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # 4️⃣ Terraform Init
      - name: Terraform Init
        working-directory: ./task5_terraform
        run: terraform init -upgrade

      # 5️⃣ Clean old plan & state
      - name: Clean old plan and state
        working-directory: ./task5_terraform
        run: |
          rm -f tfplan
          rm -f terraform.tfstate*
          rm -rf .terraform

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        working-directory: ./task5_terraform
        run: terraform plan -out=tfplan -var="docker_image=${{ github.event.inputs.docker_image }}"

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        working-directory: ./task5_terraform
        run: terraform apply -auto-approve tfplan
