name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Docker image tag (from CI pipeline)"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Debug files
      - name: Show repo files
        run: ls -R

      # 3️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 4️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # 5️⃣ Terraform Init
      - name: Terraform Init
        working-directory: ./task5_terraform
        run: terraform init

      # 6️⃣ Remove any old plan
      - name: Clean old plan
        working-directory: ./task5_terraform
        run: rm -f tfplan

      # 7️⃣ Terraform Plan (fresh every run)
      - name: Terraform Plan
        working-directory: ./task5_terraform
        run: terraform plan -out=tfplan \
          -var="docker_image=${{ github.event.inputs.docker_image }}"

      # 8️⃣ Terraform Apply
      - name: Terraform Apply
        working-directory: ./task5_terraform
        run: terraform apply -auto-approve tfplan
