name: CD - Deploy Strapi on EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -input=false -out=tfplan \
          -var "docker_image=${{ secrets.DOCKER_USERNAME }}/strapi:${{ env.image_tag }}"

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -input=false -auto-approve tfplan
